server:
  port: 7201
spring:
  application:
    name: paystore
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://58.27:3306/sys?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username:
    password:
    initialSize: 1  #初始化大小
    minIdle: 1  #空闲连接池的大小
  redis:
    database:
    host:
    port:
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
    healthcheck:
      # 开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
#MyBatis配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
#日志打印SQL
logging:
  level:
    com.vicmob: debug  #日志级别
  config: classpath:logback-spring.xml  #加载指定日志文件
#接口文档
swagger:
  enable: true #是否开启swagger