server:
  port: 6001
spring:
  application:
    name: server-eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #关闭自我保护模式
    enableSelfPreservation: false
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000