server:
  port: 7101
spring:
  application:
    name: payag
  servlet:
    multipart:
      max-request-size: 30Mb
      max-file-size: 30MB
#  tomcat:
#  uri-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url:
    username:
    password:
    initialSize: 1  #初始化大小
    minIdle: 1  #空闲连接池的大小
    maxActive: 50 #最大激活数量
  redis:
    database: 0
    host:
    port:
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
    healthcheck:
      # 开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
      # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 5
      # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
#MyBatis配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
#日志打印SQL
logging:
  level:
    com.vicmob: debug  #日志级别
  config: classpath:logback-spring.xml  #加载指定日志文件
#接口文档
swagger:
  enable: true #是否开启swagger




